# Generated by Django 3.2 on 2024-04-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='address',
            field=models.CharField(default='india', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='names',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
