# Generated by Django 3.2 on 2024-04-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autosearch', '0002_auto_20240401_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='address',
        ),
    ]
