# Generated by Django 3.2 on 2024-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosearch', '0003_remove_names_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='address',
            field=models.CharField(default='India', max_length=200),
            preserve_default=False,
        ),
    ]
